---
openapi: 3.0.2
info:
  title: simple-api
  version: 1.0.0
paths:
  /first-path:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: integer
          description: Good API
